### ISSUE TITLE
Admin is able to set negative values for price mrp and count in stock in create and edit product

### ISSUE THREAD

**Issue by s-vamshi** [roopeshsn/freshbey#100]
**Describe the bug**
Admin is able to set negative values for price mrp and count in stock fields which is meaningless in create and edit product screens.

**To Reproduce**
1. Go to /admin/createproduct
2. Try to set negative values for number type input fields

**Expected behavior**
We need to be able to set positive values only.

**Screenshots**
![image](https://user-images.githubusercontent.com/62489114/196027859-eeef7ee1-2aa7-410e-a0ae-f71927fa4c6d.png)

**Comment by s-vamshi** [comment]
@roopeshsn I would like to work on this. Can you assign this to me?

**Comment by roopeshsn** [comment]
Sure @s-vamshi
