### ISSUE TITLE
Bug in order page

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#101]
**Describe the bug**
On the order page if an admin orders a product, the status of payment and delivery is not updated when the "Mark as paid" button is clicked. The status is updated when the page is refreshed.

[updation_bug.webm](https://user-images.githubusercontent.com/70762571/196028523-3068a1a1-a3ba-4733-a4a4-3ec3fca89eac.webm)

**To Reproduce**
1. Login with the admin account (check the readme.md for the credentials)
2. Add a product to the cart
3. Click on the "Proceed to checkout" button on the cart page
4. Enter the address and select the payment option
5. Click on the "Mark as Paid" button
6. Refresh the page
7. See the payment status is updated
8. Click on the "Mark as Delivered" button
9. See the delivery status is updated

**Expected behavior**
The status message should be updated without refreshing the page.

**Screenshots**
_No Response_

**Desktop (please complete the following information):**
_No Response_

**Smartphone (please complete the following information):**
_No Response_

**Additional context**
_No Response_

**Comment by felizj17** [comment]
I'd like to work on this

**Comment by roopeshsn** [comment]
Have you found out about the bug?
