### ISSUE TITLE
User info are saved in local storage which is vulnerable to user

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#102]
The user information like email, password, token are saved in local storage which is vulnerable to user privacy. Come up with a solution to address this issue.

![userinfo_local_freshbey](https://user-images.githubusercontent.com/70762571/196029856-c5524723-f772-496d-af9a-393223bd9b00.jpg)

**Comment by s-vamshi** [comment]
@roopeshsn i would like to work on this issue. Can you assign this to me?
My approach is in the backend we need to only send token after login or sign in

**Comment by roopeshsn** [comment]
So It won't save the credentials in local storage, right?

**Comment by s-vamshi** [comment]
Yes it won't get stored except jwt.

**Comment by roopeshsn** [comment]
> local storage does the same thing as cookie right? Just curious, is there any specific reason for storing jwt in cookie?

https://coolgk.medium.com/localstorage-vs-cookie-for-jwt-access-token-war-in-short-943fb23239ca

**Comment by ozair-dev** [comment]
@s-vamshi localStorage can be accessed by the browser but the **cookies** are 'set and read' only by the backend and client doesn't have any control over it.

**Comment by ozair-dev** [comment]
@roopeshsn u can assign it to me if @s-vamshi is not available.

**Comment by s-vamshi** [comment]
@roopeshsn I caught up with some other work so you can assign it to @ozair-dev.

**Comment by roopeshsn** [comment]
You can work on this issue @ozair-dev!
