### ISSUE TITLE
Style Shopping Cart Page

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#18]
Here's the shopping cart page of Freshbey

![cart-freshbey](https://user-images.githubusercontent.com/70762571/164882256-58c6ccf9-cb54-4e28-9a3a-73ca0b1ffafe.png)

The position of the elements is not perfectly aligned. Style it as you like. But follow the color theme!

React Bootstrap is used for styling. Also, the Zephyr theme is used from Bootswatch.

**Comment by roopeshsn** [comment]
When raising your PR, attach the screenshot of the finished shopping cart page.

**Comment by imSmaity** [comment]
You can use img-fluid.

**Comment by emilylubkert** [comment]
I'd like to work on this!

**Comment by roopeshsn** [comment]
Sure, Go ahead!

**Comment by emilylubkert** [comment]
Does this look good?
![Screen Shot 2022-05-04 at 11 04 16 AM](https://user-images.githubusercontent.com/93680915/166741376-22a32ead-fb17-4b3b-bbcb-353503400cc5.png)

**Comment by roopeshsn** [comment]
Nice! Whether it is responsive on smaller screens?

**Comment by emilylubkert** [comment]
Yep! Here is how it looks on several different screen sizes.
**XL:**
![freshbey_xl](https://user-images.githubusercontent.com/93680915/166950180-badaa5fb-a873-454d-b0bf-d559b79717fe.png)
**L:**
![freshbey_l](https://user-images.githubusercontent.com/93680915/166950204-dbffe655-5c7a-4959-815e-f970c6710781.png)
**M:**
![freshbey_m](https://user-images.githubusercontent.com/93680915/166950218-ae80b3a1-e6a0-42ea-9416-a9f05e85d978.png)
**S:**
![freshbey_s](https://user-images.githubusercontent.com/93680915/166950234-4a1a50e7-731d-425a-bf89-13bd145e3ff5.png)

**Comment by vansh12345341** [comment]
Hey i would like to style this cart page for you ....can you describe me how you want it too look ?

**Comment by xscottxbrownx** [comment]
Seems like you enjoyed @emilylubkert work...  is this issue ready to be closed?  Or did you have more in mind @roopeshsn ?
