### ISSUE TITLE
ProfileScreen update label for "Password" field

### ISSUE THREAD

**Issue by jjaijg** [roopeshsn/freshbey#30]
![image](https://user-images.githubusercontent.com/22398917/184098137-be8db0fd-c7c5-43e7-a258-76421185dc9d.png)

**Comment by jjaijg** [comment]
I have created PR for this issue.
[https://github.com/roopeshsn/freshbey/pull/29](https://github.com/roopeshsn/freshbey/pull/29)

**Comment by dharmiknotop** [comment]
hey, what kind of updation?

**Comment by jjaijg** [comment]
Hi @dharmiknotop, it's just a UI change. Changed label "Password Address" to "Password"

**Comment by dharmiknotop** [comment]
ohk, can you assign this to me?

**Comment by jjaijg** [comment]
Actually I have already created a pull request for this [#29](https://github.com/roopeshsn/freshbey/pull/29).
And I am not the Author/maintainer, I won't be able to assign it to you
