### ISSUE TITLE
Suggestions on Payment Gateway

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#37]
I am thinking is there any way to add a payment gateway without using services like Paypal, Stripe, or Razorpay?

**Comment by sameergupta4873** [comment]
i have added this stuffs like Paypal and Razorpay , they work greatly on my website on github : -
do checkout :- [here](https://github.com/sameergupta4873/ecommerce_website.git)
payment :- [walkthrough video](https://www.linkedin.com/posts/sameer-gupta-a29272184_frontend-project-share-activity-6975860047784349697-Fis_?utm_source=share&utm_medium=member_desktop)

**Comment by SyedMuzamilM** [comment]
I think we should support more payment methods like stripe PayPal rayzorpay. And any one choosing this project can choose one of them or all
