### ISSUE TITLE
Change project setup env in README

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#38]
I have given my own credentials in env variables under "Getting Started - Project setup on your local machine" in the README file. Change those in order to set up those accounts by the developer itself.

**Comment by roopeshsn** [comment]
Hi, @Aryangp Similar to this I need the env setup to be written in the readme.

![env-setup-documentation](https://user-images.githubusercontent.com/70762571/193485805-f3cf3001-e630-44c2-a708-ed44c0b76e0d.png)

If you observe that there are no credentials data. That means the developer can set up their own accounts to work with this project (eg. MongoDB, etc.)

**Comment by Aryangp** [comment]
Yeah i can do that pls assign this issue to me

**Comment by roopeshsn** [comment]
Hi, I have assigned you @Aryangp Feel free to ask if you have any queries.

**Comment by Aryangp** [comment]
Thanks

**Comment by roopeshsn** [comment]
Hi! Make sure to use this command frequently because we have more changes taking place often 

git fetch upstream master

**Comment by Aryangp** [comment]
ok sure
