### ISSUE TITLE
Data from the database (MongoDB) is not loading

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#40]
The problem I have found is that data from MongoDB is not loading. Though the cluster is working properly. Attached the necessary screenshots. 

![screenshot-freshbey herokuapp com-2022 10 02-14_34_45](https://user-images.githubusercontent.com/70762571/193446690-5b176561-f3ad-4e3e-9a6f-ce8858bd7752.png)

![screenshot-cloud mongodb com-2022 10 02-14_36_37](https://user-images.githubusercontent.com/70762571/193446736-72b71cf6-c378-4475-97cc-6f59a6f99b55.png)

**Comment by leksyking** [comment]
Please confirm if there are products in the database collection

**Comment by roopeshsn** [comment]
I have destroyed the DB and imported it again. Now the problem is solved. As I have given my original credentials for MongoDB someone has changed the products collection. I need to remove those credentials.

**Comment by leksyking** [comment]
Okay good, kindly close the issue
