### ISSUE TITLE
Suggestions on separating backend and frontend

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#41]
As of now the backend and frontend are tied up together. I would like to separate them out so that hosting can be done without hassle. This will help in further scalability.

**Comment by SyedMuzamilM** [comment]
I would like to help.
Basically we can have separate npm projects for both front-end and backend.
We can have mono repo the same way it currently is and then if you want backend can be hosted on AWS EC2 which is free for a year and front-end on vercel or netllify

**Comment by roopeshsn** [comment]
Instead of having separate repositories can't, we do the partition in the same repo?

**Comment by itsvipindev** [comment]
I think we can separate both the client side and server side by creating different folders for each and find a way to make them communicate to each other like rendering dynamic page with jsx or change the HTML file with according to JSON data we recive from server side

**Comment by SyedMuzamilM** [comment]
> Instead of having separate repositories can't, we do the partition in the same repo?

We can use mono repo. Both front-end and backend in the same repo but can be deployed separately

**Comment by roopeshsn** [comment]
Hi, @SyedMuzamilM Have you worked like the same thing previously? If so we can work and separate the repos for EC2.

**Comment by SyedMuzamilM** [comment]
Yes I have worked that way. And we can separate the backend and front-end. And then on a single push it can get deployed to backend or front-end depending upon where the Changes have happened
