### ISSUE TITLE
[Feature] Dark Mode 🌙

### ISSUE THREAD

**Issue by AjayMaheshwari23** [roopeshsn/freshbey#48]
Some users prefer viewing the website in dark mode for better visibility . So can i contribute to this repository by adding a button which will help to switch between light and dark mode . can you assign it to me .

**Comment by AmreshSinha** [comment]
Hey, are you working on this? If not, I would love to work on this!

**Comment by AjayMaheshwari23** [comment]
I want to work on this , created theme and other stuff just waiting for owner of this repo to assign it to me .

**Comment by roopeshsn** [comment]
Hi, @AjayMaheshwari23 Thanks for your interest! I am planning to change the frontend style to Chakra UI from Bootstrap. Right now this feature is not necessary.

**Comment by AjayMaheshwari23** [comment]
If in future , you plan to add dark mode , do assign it to me  .
