### ISSUE TITLE
Render a message if a user has not bought anything

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#50]
This is the profile page of a user.

![screenshot-freshbey herokuapp com-2022 10 03-13_58_42](https://user-images.githubusercontent.com/70762571/193533722-1c6d94c8-620c-4452-9fe3-d922c2130f0d.png)

In the profile, there is a "My Orders" section. If a user has not bought anything there is a message below the table stating that "You haven't placed any order yet, [Start Shopping!](https://freshbey.herokuapp.com/)

**Comment by ankitdas09** [comment]
I can work on this, can you please assign it to me?

**Comment by roopeshsn** [comment]
Sure @ankitdas09  I would like to say something. On commit, don't add the package-lock.json file. Because it continuously changes if the new version of the packages is available. It will unnecessarily raise merge conflict.

**Comment by ankitdas09** [comment]
@roopeshsn Sure, i will take care of that.
