### ISSUE TITLE
Render appropriate message if a order eligible for free delivery or not

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#51]
Render a message similar to this on the Freshbey cart page if the order was above Rs. 400.

![order_eligible_for_free_delivery](https://user-images.githubusercontent.com/70762571/193540628-bbdca63f-6958-45b1-8efd-94a315aa55d8.jpg)

else render a message stating that how much extra to add so that the order qualifies for free delivery.

![not_eligible_for_free_delivery](https://user-images.githubusercontent.com/70762571/193540935-ffc9e9c7-65c5-4a22-9aba-cbfde2d47488.jpg)

Also, take care of the shipping charges on the place order page. If the user is eligible for free delivery, then the shipping charges should be 0 else the shipping will be Rs. 40.

![freshbey_placeorder_page](https://user-images.githubusercontent.com/70762571/193542482-4c4782c5-c8d7-4091-85e7-5bd4029e2642.jpg)

Note the images are taken from Amazon India.

**Comment by juliana-mol** [comment]
Can I work on this ?

**Comment by roopeshsn** [comment]
But it seems that you joined Github yesterday.

**Comment by ankitdas09** [comment]
@roopeshsn can i work on this?

**Comment by CIC4DA** [comment]
@roopeshsn I would love to work on this issue!

**Comment by roopeshsn** [comment]
Hi, @ankitdas09 Could you explain your approach to solving this problem? The message should be rendered on the cart page as well as the place order page.

**Comment by roopeshsn** [comment]
Hi, @ankitdas09 Make sure the message should render on both the cart and shipping pages. If you would like to add the shipping pricing to the cart page you're welcome to do that.

**Comment by ankitdas09** [comment]
@roopeshsn Sure. Please assign.
