### ISSUE TITLE
Create Image upload component for products admin page

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#54]
For admin, there is an option to create a new product.

![admin_product_page_freshbey](https://user-images.githubusercontent.com/70762571/193722025-89b729f8-ec90-4779-ae2d-d9e8e3e1313c.jpg)

Here is the form when you click that "Create Product" button.

![create_product_form_freshbey](https://user-images.githubusercontent.com/70762571/193722373-f3d668bb-e6cd-461a-8a0d-56d0c6900ec4.png)

For the Image Src field, Freshbey uses [ImgBB](https://imgbb.com/) service. ImgBB is an image hosting service. You can host images and get direct links. If I want to add an image, I'll manually go to ImgBB and upload the image and I will get the direct link. I'll then paste that link into this "Img Src" field. After that when I click the "Update" button the data will be stored in the Database.

As you see this is a very hectic process. I don't want admins or editors to go to that ImgBB service to upload the product image. Create an image upload component so that we can directly upload the image from the local system. That image should directly store in the database.

We have the "Edit Product" option. Take care of the image upload there too.

![edit_product_freshbey](https://user-images.githubusercontent.com/70762571/193723968-fe63a069-47b9-4047-bd18-a21d0d86750b.jpg)

![edit_product_page_freshbey](https://user-images.githubusercontent.com/70762571/193724199-8d53793e-e9cc-4cb9-b591-c2a82bd32bba.png)

If you have any queries feel free to reach out. Also, if you have any other solutions do let me know!

**Comment by s-vamshi** [comment]
Hey i would like to work on this. I have few doubts, so instead of manually uploading to ImgBB, admin need to upload file to the DB right?

**Comment by roopeshsn** [comment]
Yes, you're right! Also, you should take care of rendering the images in the frontend. Could you explain doing this? Also if you have another solution you're welcome to discuss it.

**Comment by s-vamshi** [comment]
I have done some research about storing files directly in mongodb and i got to know that it is not the best way but we can try.
and i have a solution like if there is a way to use imgBB API then what we can do is as soon as user uploads the image we can send a request to save in imgBB and then if it can send a response which has success and url(link of image) attributes and upon success we can prefill the hidden input file with the url and update

**Comment by s-vamshi** [comment]
And yes, imgBB provides API so we can use the api service and upload

**Comment by s-vamshi** [comment]
Seems like cloudinary is the next better option.

**Comment by s-vamshi** [comment]
@roopeshsn i have a doubt in case if we are using cloudinary then i need to add a new env variable of api key given by cloudinary and then if everything goes well you are going to merge and then you are going set a new env variable as cloudinary api key in heroku dashboard then deploy. This is the flow right ?

**Comment by roopeshsn** [comment]
Yes, you're right!

**Comment by s-vamshi** [comment]
so should i start working on this?

**Comment by roopeshsn** [comment]
Yeah, go ahead! Work on a new branch. We'll discuss weekly the progress.

**Comment by s-vamshi** [comment]
Sure.

**Comment by roopeshsn** [comment]
Could you share what that review looks like?

**Comment by s-vamshi** [comment]
I haven't worked on it but beside file input field we can show preview.
I have made PR where we can upload images directly to cloudinary, can you please check?
#74

**Comment by roopeshsn** [comment]
I will review the code and let you know tomorrow. Also, add screenshots of your work.

**Comment by s-vamshi** [comment]
Sure!

**Comment by s-vamshi** [comment]
Here is the working demo -


https://user-images.githubusercontent.com/62489114/194121496-ea9daa86-6af6-4493-b605-c7d0b9fb813d.mp4

**Comment by s-vamshi** [comment]
@roopeshsn i have made few modifications to CreateProduct page which are 
1. Image src label changed to Product image
2. Set the Image Source field as readOnly. Reason - after uploading image user might change the src path.
3. Changed the order of input (Image Src and File Upload) fields. Reason - before image src input field used to be encountered by the user, as I have made img src field as readOnly user may try to focus the field and might not know that img src input field will get populated after file(image) upload so what i thought was if we place file upload input above then users will upload and then after successfully uploading they might not care about img src field as link will get populated automatically in it.

Any thoughts on this changes?

Here is the demo -

![tem4](https://user-images.githubusercontent.com/62489114/194278615-1b2b6cbb-bfd2-4e8e-ad2d-31b91aedab00.PNG)
Haven't pushed this changes yet!

**Comment by s-vamshi** [comment]
> Could you share what that review looks like?

Here is the view :-

**Desktop View -**
![temp4](https://user-images.githubusercontent.com/62489114/194324386-f8b6e203-a4a3-4206-8bec-ffabc0956f51.PNG)

**Mobile View -**
![tem5](https://user-images.githubusercontent.com/62489114/194324414-5061a07f-69a4-4f6d-a157-203add50604c.PNG)

**Comment by roopeshsn** [comment]
> @roopeshsn Here is the working demo -
> 
>  screen-capture.1.mp4

Could you also show the product page with the image, description, and pricing?

**Comment by s-vamshi** [comment]
> > @roopeshsn Here is the working demo -
> > screen-capture.1.mp4
> 
> Could you also show the product page with the image, description, and pricing?

![tem6](https://user-images.githubusercontent.com/62489114/194331542-f593f533-b2a4-4da5-9d46-d3880734c74d.PNG)

![tem7](https://user-images.githubusercontent.com/62489114/194331584-e0d42b53-b49c-4f5f-8f9e-f5e77587fa34.PNG)

**Comment by roopeshsn** [comment]
> > How will it be if that path component is removed? Bear with me for delaying accepting the PR as I don't find time to review the code.
> 
> No problem😃. I didn't get you, like are you asking what happens if img src value has empty string?

No, I am saying that remove the img path component. Why do we need to show the path of the image to the user?

![screenshot-github com-2022 10 06-19_44_05](https://user-images.githubusercontent.com/70762571/194336336-4a55fef4-a62d-42de-bed2-965d5b667b3e.png)

**Comment by s-vamshi** [comment]
> > Could you share what that review looks like?
> 
> Here is the view :-
> 
> **Desktop View -** ![temp4](https://user-images.githubusercontent.com/62489114/194324386-f8b6e203-a4a3-4206-8bec-ffabc0956f51.PNG)
> 
> **Mobile View -** ![tem5](https://user-images.githubusercontent.com/62489114/194324414-5061a07f-69a4-4f6d-a157-203add50604c.PNG)

is this view ok?

**Comment by roopeshsn** [comment]
> Yes we can remove path input field and there is no specific reason for showing the path to user. This will be the view if we remove path component ![tem8](https://user-images.githubusercontent.com/62489114/194342080-63229f72-c3bf-442c-b354-08405346d133.PNG)

Nice
