### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#55]
If a user bought a product, the count should be reduced from the stock automatically. Till now there is no option like this. Come up with a solution that solves the problem as stated.

**Comment by codeDude64** [comment]
May you assign me this issue? please.

**Comment by roopeshsn** [comment]
Could you explain your approach?

**Comment by djsteinmetz** [comment]
I would work on this.  My approach would be to decrement the inventory of the item from within the orderController. After the order is successfully saved, I would call the product controller method updateProduct to decrement the inventory by the amount of the completed order.

**Comment by roopeshsn** [comment]
Hi, @djsteinmetz Thanks for your interest in this issue! If an order is successfully placed, you will call this updateStocksInCount function not updateProduct right?

**Comment by BiswajitSahoo-tech** [comment]
Hi @djsteinmetz 
I want to work on this issue, my approach would be like this:

1. when the user paid for an order, that order is now successfully placed. In this case, we call the `updateOrderToPaid` route handler.
2. In `updateOrderToPaid` we have access to the current order by this code line
    `const order = await Order.findById(req.params.id)`
3. Each order document has an **OrderItem**, an array of `productId`, and other info
4. So, we just iterate over all the items on **OrderItem** and do something like this
```
orderItems.forEach(async (item) => {
     const id = item.product
     await updateStockCount( id)
  })
```
5. `updateStockCount( id)` is a middleware defined on poductController, which will update the `countInStock` field of the given product. below is the code for that
  ```
const updateStockCount =async  ( id) => {
      await Product.findByIdAndUpdate( id , {
           $inc: {
                countInStock: -1
           }
      } )
  }
```

**Comment by roopeshsn** [comment]
> Hi @djsteinmetz I want to work on this issue, my approach would be like this:
> 
> 1. when the user paid for an order, that order is now successfully placed. In this case, we call the `updateOrderToPaid` route handler.
> 2. In `updateOrderToPaid` we have access to the current order by this code line
>    `const order = await Order.findById(req.params.id)`
> 3. Each order document has an **OrderItem**, an array of `productId`, and other info
> 4. So, we just iterate over all the items on **OrderItem** and do something like this
> 
> ```
> orderItems.forEach(async (item) => {
>      const id = item.product
>      await updateStockCount( id)
>   })
> ```
> 
> 5. `updateStockCount( id)` is a middleware defined on `controller/poductController.js` , which will update the `countInStock` field of the given product. below is the code for that
> 
> ```
> const updateStockCount =async  ( id) => {
>     await Product.findByIdAndUpdate( id , {
>          $inc: {
>               countInStock: -1
>          }
>     } )
> }
> ```

Actually, you should have mentioned me not @djsteinmetz Just kidding!

**Comment by BiswajitSahoo-tech** [comment]
Yes @roopeshsn
Very much interested to work on this.
