### ISSUE TITLE
Change color on focus in input fields

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#59]
Freshbey's primary color is #34a853. It is declared as a variable "--bs-green" in the index.css file. So we want this color to be referenced as primary all over the application. Be it has hover, focus, etc. we need these shades of color to be referenced. But in the input field, when focused, a shade of blue is shown. This behavior is shown below through a screenshot.

![freshbey_focus_color](https://user-images.githubusercontent.com/70762571/193786805-7fdb3bc8-d9de-40ad-8e2d-5d26ec127c0d.png)

Change this focus color to be --bs-green for every input field.

**Comment by heisdinesh** [comment]
can i work on this issue @roopeshsn

**Comment by roopeshsn** [comment]
Hi @heisdinesh Sure, you can work on this. Reference the README file for styling libraries and themes used in this project.

**Comment by roopeshsn** [comment]
Hi @heisdinesh If you're not working on this issue let me know. I can unassign you so that others can work.

**Comment by heisdinesh** [comment]
Sir i am figuring out, how to do this, sure you can unassign me as it is taking long time, thanks for the opportunity

**Comment by Aryan-Bhatt-pro** [comment]
Hi @roopeshsn, is the issue assigned to anyone? I would like to contribute to it

**Comment by roopeshsn** [comment]
You can work on this issue @Aryan-Bhatt-pro

**Comment by roopeshsn** [comment]
Hey, @Aryan-Bhatt-pro Have you completed the work assigned to you?

**Comment by roopeshsn** [comment]
This issue is still open.

**Comment by ranjankuldeep** [comment]
I Would like to contribute.
 Please assign it to me.
@roopeshsn.

**Comment by ranjankuldeep** [comment]
###  just need a go-ahead, I already changed the color to all Input Fields. @roopeshsn 
<img width="1440" alt="Screenshot 2022-10-13 at 8 04 29 PM" src="https://user-images.githubusercontent.com/95350799/195626871-3d9343fe-5659-453e-b37f-34d6fdc32b0d.png">

**Comment by roopeshsn** [comment]
This issue is still open!

**Comment by ranjankuldeep** [comment]
ya I worked on that and fixed that, assign me so that I generate the PR.

**Comment by roopeshsn** [comment]
I don't want you to commit this feature along with that search box changes. Work on the new branch and commit the changes for this feature alone. Is that clear?

**Comment by ranjankuldeep** [comment]
yes,
I will make a new branch.
