### ISSUE TITLE
Enable text compression

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#6]
Lighthouse states that Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes.

![text-compression-lighthouse](https://user-images.githubusercontent.com/70762571/152955021-342fee3d-722e-443f-acea-547506c34821.jpg)
 
You can learn more here: [https://web.dev/uses-text-compression/?utm_source=lighthouse&utm_medium=devtools](url)

**Comment by developedBySJ** [comment]
@roopeshsn can I work on this?

**Comment by roopeshsn** [comment]
Sure

**Comment by roopeshsn** [comment]
Have you tested the application in your local machine before raising a PR?

**Comment by developedBySJ** [comment]
Yes, I have tested the application in production mode.

![image](https://user-images.githubusercontent.com/76519654/160386779-6375c088-8de0-4c49-8e50-031ecd94ebbe.png)

**Comment by roopeshsn** [comment]
Good work @developedBySJ

**Comment by roopeshsn** [comment]
I would like you to be an active maintainer of this project. If you spot any bugs or performance-related issues please create an issue. So, that others can work on that. If you'd like to add any new feature please go ahead.  Your contribution will highly benefit this project!
