### ISSUE TITLE
Change logo's font style and color

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#60]
To differentiate the logo text "Freshbey" in the navbar, I need the font and color to be changed.

Desired font style: League Spartan Semi Bold 600
Desired Color: --bg-green (declared in the index.css file)

![fresbey_logo_change](https://user-images.githubusercontent.com/70762571/193789869-9c66ec14-d010-4519-9761-e2f5984400ee.jpg)

Note: The change should be to that particular text only.

**Comment by Utkarsh212** [comment]
Please assign this to me so that I could work on it

**Comment by tanisha-salvi** [comment]
I can work on this issue, kindly assign it to me.

**Comment by roopeshsn** [comment]
Sure you can work on this @Utkarsh212 Reference the README file for styling libraries and themes used in this project.

**Comment by Utkarsh212** [comment]
@roopeshsn sure

**Comment by Utkarsh212** [comment]
@roopeshsn I have fixed the issue. Refer PR: #62
