### ISSUE TITLE
[FEATURE] Wishlist

### ISSUE THREAD

**Issue by SyedMuzamilM** [roopeshsn/freshbey#68]
Sometimes, a customer may be interested in a product but decide to buy it later. Or a customer may find a product interesting and want to check that later for more details. A wishlist allows them to store a list of these products so that they can easily find them next time they visit your site.

**Comment by janmesh799** [comment]
can you specify in which part wishlist have to be developed 
like in backend or frontend

**Comment by SyedMuzamilM** [comment]
So it will be developed in the both parts. You have to create the model for wishlist first which would include the user id and the products that he has wishlist. After that you need to create app for it so that it can be used on front-end.
And then implement that api on the front-end to include whichlisht icon on the header which should take to the wishlist page where you need to show all the products from that user.
And you also need to add the wishlist add or remove icon on the product where user can add or remove the product from wishlisht

**Comment by janmesh799** [comment]
can you break this issue in 2-3 parts 
so, it can became easy for contributing.

**Comment by SyedMuzamilM** [comment]
Can you explain what you can do here

**Comment by janmesh799** [comment]
as a full stack developer i am comfortable in both backend and front-end.

**Comment by SyedMuzamilM** [comment]
So you can first start creating the api for this

**Comment by janmesh799** [comment]
sure ,
then, can you assign this to me

**Comment by janmesh799** [comment]
endpoints
1. adding to wishlist 
2. removing from wishlist

any suggestions other than these

**Comment by roopeshsn** [comment]
Hi @janmesh799 Why can't we keep the wishlist in the local storage itself? Because the cart items are also stored in local storage. So you can implement this feature in the frontend itself.

**Comment by janmesh799** [comment]
yes, i can do this

**Comment by roopeshsn** [comment]
Hi, @janmesh799 With discussions with @SyedMuzamilM It has been decided to save both the cart and wishlist data in the database, not in local storage. Whether you're interested to work on this. If you feel that it's huge then work for the wishlist feature alone. What's your take?

**Comment by janmesh799** [comment]
I think, saving in database makes more sense than saving in local storage.

If user uses application on more than 1 platform , then database would be best choice for retrieving the date for cart and wishlist

**Comment by roopeshsn** [comment]
Yeah, @SyedMuzamilM also said the same! What's your take @janmesh799?

**Comment by janmesh799** [comment]
I can integrate cart and wishlist with database

**Comment by janmesh799** [comment]
We should go with database option

**Comment by roopeshsn** [comment]
Sure @janmesh799 Go ahead!

**Comment by SyedMuzamilM** [comment]
> endpoints
> 
> 1. adding to wishlist
> 2. removing from wishlist
> 
> any suggestions other than these

Also there will be the endpoint to show all the wishlisted items of a user

**Comment by janmesh799** [comment]
cool ✌

**Comment by roopeshsn** [comment]
Hey, @janmesh799 Have you completed the work assigned to you?
