### ISSUE TITLE
Stylish Hover Effect In Category

### ISSUE THREAD

**Issue by HridoyHazard** [roopeshsn/freshbey#69]
Want Add Stylish Hover Effect In Category So When User Move Their Cursor To Category They Will Get Beautiful Hover Effect
kindly assign this to me

**Comment by roopeshsn** [comment]
Go ahead @HridoyHazard But make sure that the effect will be aligned to the theme and colors. It should be neat and minimal.

**Comment by roopeshsn** [comment]
Hi, @HridoyHazard Have you working on this issue? If not I'll unassign you so that others can work.

**Comment by jarus1029** [comment]
Hey!! Can You assign me this task ???
I can work on this as specified by you...

**Comment by roopeshsn** [comment]
Go ahead @jarus1029 But make sure that the effect will be aligned to the theme and colors. It should be neat and minimal.

**Comment by roopeshsn** [comment]
Hey, @jarus1029 Have you completed the work assigned to you?
