### ISSUE TITLE
Add validation in backend using Joi

### ISSUE THREAD

**Issue by SyedMuzamilM** [roopeshsn/freshbey#70]
**Is your feature request related to a problem? Please describe.**
User can send any thing to the backend and that unwanted data can be stored in the database.

**Describe the solution you'd like**
In order to prevent the unwanted data to get stored in the database we should be validating the data comming to the backend.
So we should be using Joi as a validation library to validate each request

**Describe alternatives you've considered**
We could also use custom validation but I thing it would be better to use Joi as it is popular and would be easy.

**Comment by roopeshsn** [comment]
@SyedMuzamilM is working on this issue. Have you finished working on this issue @SyedMuzamilM?

**Comment by SyedMuzamilM** [comment]
Yes almost finished it. You can assign @DreuXXX  this task. I am busy with some work. Will not be able to work on this for some time. Once I get some time I will work on some other taks.
