### ISSUE TITLE
Create footer section

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#72]
**Is your feature request related to a problem? Please describe.**
Freshbey's footer doesn't have enough information.

**Describe the solution you'd like**
Create a footer similar to the screenshot attached.

**Describe alternatives you've considered**
_No response_

**Additional context**

![footer_freshbey](https://user-images.githubusercontent.com/70762571/194012720-664f3be8-2912-48af-8f91-3bbbd2a0df13.png)
Note: Image is taken from Flipkart

Take care that the footer should be responsive for smaller displays too. Reference the README file for styling libraries and themes used in this project.

**Comment by masterHAWK99** [comment]
Please assign me, I started working on it.
