### ISSUE TITLE
Hash password before storing 

### ISSUE THREAD

**Issue by akshat-rawat** [roopeshsn/freshbey#77]
**Is your feature request related to a problem? Please describe.**
The passwords being stored are not hashed, this is a security concern while developing e-commerce websites.

**Describe the solution you'd like**
Before storing passwords we can hash it, alternatively before making the API request to backend we can hash the password then we can store it.

**Describe alternatives you've considered**
none.

**Additional context**
This will lead to breaking changes for existing users, we can either register every user again or we'll have to hash passwords already present in database.

Lastly, I would like to work on this issue.

**Comment by roopeshsn** [comment]
Hi @akshat-rawat Hashing of a password is implemented in userModel.js https://github.com/roopeshsn/freshbey/blob/a61c420b5ceb4eb96142161887b49632a1d4bc12/backend/models/userModel.js#L51
