### ISSUE TITLE
Search box shouldn't appear in the /login route

### ISSUE THREAD

**Issue by gkupdx** [roopeshsn/freshbey#79]
Currently, clicking on "Login / Sign Up" redirects you to /login with this on the page:

![image](https://user-images.githubusercontent.com/32969781/194681542-78132df4-32dc-46cf-ab2b-88245b10bbdf.png)

But I don't think it makes any intuitive sense for a search box to be in the /login route. 
I can see that the search box is being rendered in the Header.js component. Is there a specific reason as to why the search box is being rendered in that component and not, for example, in the HomeScreen.js component?

I am also willing to work on this issue.

**Comment by roopeshsn** [comment]
Hi @gkupdx You're right we don't need the search box in the login, register, and forgot password routes. You can work on this.

**Comment by gkupdx** [comment]
@roopeshsn Is it okay if I just remove the search box from HomeScreen.js as well? I think you wanted to move the search box into the header bar anyways.

**Comment by roopeshsn** [comment]
> @roopeshsn Is it okay if I just remove the search box from HomeScreen.js as well? I think you wanted to move the search box into the header bar anyways.

No

**Comment by gkupdx** [comment]
@roopeshsn Okay, I think I got this issue fixed. Just had one question: is it okay if I include a very minor refactor in the commit?
I just wanted to replace a ternary operator with the && operator in Header.js: 

From this:
![image](https://user-images.githubusercontent.com/32969781/194780429-107fe3eb-efba-48ea-95c3-b981f19d97a5.png)

To this:
![image](https://user-images.githubusercontent.com/32969781/194780435-4c141d5a-907f-430c-b664-0ed3e5c809c3.png)

The functionality should be the same and I think it'll help clean-up the code a bit.

**Comment by roopeshsn** [comment]
> @roopeshsn Okay, I think I got this issue fixed. Just had one question: is it okay if I include a very minor refactor in the commit? I just wanted to replace a ternary operator with the && operator in Header.js:
> 
> From this: ![image](https://user-images.githubusercontent.com/32969781/194780429-107fe3eb-efba-48ea-95c3-b981f19d97a5.png)
> 
> To this: ![image](https://user-images.githubusercontent.com/32969781/194780435-4c141d5a-907f-430c-b664-0ed3e5c809c3.png)
> 
> The functionality should be the same and I think it'll help clean-up the code a bit.

No problem
