### ISSUE TITLE
Previous and Next buttons are not visible in the carousel component

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#81]
In the Carousel component, the previous and next buttons are not properly visible to the user. 

![slider_button_not_visible](https://user-images.githubusercontent.com/70762571/194708439-8283c597-7e9c-433a-a9f4-f14e451c7cf6.png)

**Comment by ElectricPlant19** [comment]
assign this to me please i can fix it

**Comment by roopeshsn** [comment]
Hi, @ElectricPlant19 Could you share your approach to doing it?

**Comment by ElectricPlant19** [comment]
> Hi, @ElectricPlant19 Could you share your approach to doing it?
 
Can be done by giving the span of the carousel a translucent tint.

**Comment by roopeshsn** [comment]
Hey, @ElectricPlant19  Have you completed the work assigned to you?

**Comment by roopeshsn** [comment]
This issue is still open!

**Comment by AyushTripathi-sketch** [comment]
#109

**Comment by AyushTripathi-sketch** [comment]
Solved the issue in pr #109

**Comment by bismuth42** [comment]
I would like to work on this issue, please assign it to me.
