### ISSUE TITLE
Place Search bar on the Navbar

### ISSUE THREAD

**Issue by roopeshsn** [roopeshsn/freshbey#82]
The search bar should be placed in the Navbar as shown in the image.

![search_box_navbar_freshbey](https://user-images.githubusercontent.com/70762571/194709197-7ab87cc4-82cc-4296-9399-0e88f247ded5.png)

**Comment by bhumika-1-3** [comment]
can you assign this to me ?

**Comment by nallammai-maruthappan** [comment]
can you assign this to me?

**Comment by bhumika-1-3** [comment]
Its already been assigned to me.

**Comment by VivekYadav98** [comment]
Hey @roopeshsn , can you  please assign this to me  ?

**Comment by Dnyanesh-Bachhav** [comment]
Hey, I have added a searchbar in header, please check it once??

**Comment by roopeshsn** [comment]
This issue is still open!

**Comment by ranjankuldeep** [comment]
Please assign it to me.. @roopeshsn

**Comment by roopeshsn** [comment]
This issue is still open!

**Comment by nallammai-maruthappan** [comment]
can you assign to me?

**Comment by roopeshsn** [comment]
But most of them who worked on this issue failed to complete the task. Will you do it?

**Comment by Supriya-48** [comment]
I would like to work on it, could you assign it to me @roopeshsn

**Comment by amanycodes** [comment]
Hey, I would like to work on this issue. Can you please assign me the task of adding the search bar on the navbar. I would appreciate it.

**Comment by roopeshsn** [comment]
Go a head @amanycodes

**Comment by gokul-srinath** [comment]
hey @roopeshsn , kindy checkout my PR 
**Search Bar added in Navigation Bar #122**
have added detailed description on the issue, please review
