### ISSUE TITLE
Page goes blank when we try to edit any product in admin/productlist page after editing one of the product before

### ISSUE THREAD

**Issue by s-vamshi** [roopeshsn/freshbey#86]
**Describe the bug**
when we are in admin/productlist route, when we click on edit button and update a product then we will get again redirected to admin/productlist. Here starts the problem now when we want to edit any other product we will get an error Uncaught TypeError: Cannot read properties of undefined (reading 'name') at ProductEditScreen.js:47:1

**To Reproduce**
1. Go to admin/productlist
2. Click on edit button for one product
3. Edit details of that product
4. Click update button
5. It will get redirect again to admin/productlist
6. Now try to edit any product it will show a blank page
7. And if we open console we get this message Uncaught TypeError: Cannot read properties of undefined (reading 'name') at ProductEditScreen.js:47:1

**Expected behavior**
We should see an edit page of that particular product.

**Screenshots**
![tem15](https://user-images.githubusercontent.com/62489114/194716159-c7a05e7a-0748-4518-9ad8-43628400d343.PNG)

**Comment by roopeshsn** [comment]
But you don't have any contribution or commit to your own repos before.

**Comment by SurajKD** [comment]
i can fix it

**Comment by roopeshsn** [comment]
Hi @SurajKD You can work on this. If you found the bug mention it precisely in your PR.

**Comment by sameersecond** [comment]
Hi @roopeshsn. Sorry I don't have any commits on this account. I have found the source of the bug and fixed it. Do you want me to create the PR or should I work on some other bug
