### ISSUE TITLE
Improve understandability of the profile screen

### ISSUE THREAD

**Issue by gkupdx** [roopeshsn/freshbey#96]
**Is your feature request related to a problem? Please describe.**
Feature is not related to a problem, it is just something I'd like to see improved.
Currently, the profile screen info looks like this:
![image](https://user-images.githubusercontent.com/32969781/195743134-f124c9d0-0b2e-47e9-837f-13c0069ca8ca.png)

But having a form be displayed under the user profile can be confusing to the user.

**Describe the solution you'd like**
I would like to change it to something like this:
![image](https://user-images.githubusercontent.com/32969781/195743286-05b1e48f-f479-461a-a627-5ce8732912fe.png)

After clicking on 'Update User Info', it shows the form:
![image](https://user-images.githubusercontent.com/32969781/195743348-02aa1a0b-d02b-47a5-87e7-08dbf5bdd0d6.png)

And after you've made changes to your profile and click "Update", it hides the form again:
![image](https://user-images.githubusercontent.com/32969781/195743593-1ca437bc-f162-483f-90d1-7abeeea81c03.png)

**Describe alternatives you've considered**
This is just the first step to improving the UI of the profile screen. I'd like to make more improvements in the future.

**Additional context**

@roopeshsn I would like to be assigned to this as well.

**Comment by roopeshsn** [comment]
Refer #94
